// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUdmIoYcSNIh2vY-86Za1u4l4sVGGCIB4',
    appId: '1:54846645341:web:716903a1928dd489a199b4',
    messagingSenderId: '54846645341',
    projectId: 'flutter-chat-62478',
    authDomain: 'flutter-chat-62478.firebaseapp.com',
    storageBucket: 'flutter-chat-62478.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZyp9YJo_hUpZ_UtzJqgixxlWDKKZ1QrM',
    appId: '1:54846645341:android:c2a5465edb58783ca199b4',
    messagingSenderId: '54846645341',
    projectId: 'flutter-chat-62478',
    storageBucket: 'flutter-chat-62478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6itwuB4ejcKrIEM_4WQcDCoEueHMtfPA',
    appId: '1:54846645341:ios:19212312a66a26d9a199b4',
    messagingSenderId: '54846645341',
    projectId: 'flutter-chat-62478',
    storageBucket: 'flutter-chat-62478.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6itwuB4ejcKrIEM_4WQcDCoEueHMtfPA',
    appId: '1:54846645341:ios:19212312a66a26d9a199b4',
    messagingSenderId: '54846645341',
    projectId: 'flutter-chat-62478',
    storageBucket: 'flutter-chat-62478.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    appId: "1:54846645341:web:716903a1928dd489a199b4",
    apiKey: "AIzaSyCUdmIoYcSNIh2vY-86Za1u4l4sVGGCIB4",
    authDomain: "flutter-chat-62478.firebaseapp.com",
    projectId: "flutter-chat-62478",
    storageBucket: "flutter-chat-62478.appspot.com",
    messagingSenderId: "54846645341",
  );

}